### ISSUE TITLE
segmentation fault when converting simple input & seemingly incorrect FSM results

### ISSUE THREAD

**Issue by Licheng-Guo** [pdclab/peregrine#10]
Hello,

I'm new to frequent graph mining and hope to use this tool as a black box.

I ran into the following issues. Could you help take a look?

1. A simple input seems to crash the `bin/convert_data`. I'm running Ubuntu 18.04

graph.txt
```
0 1
1 2
2 3
3 0
```
Command:
`bin/convert_data graph.txt test/graph_converted`

Result:
```
Read edge-list in 5.7e-05s
Segmentation fault (core dumped)
```

2. Another input could be converted by `bin/convert_data`, but I could not understand the fsm results.

```
1 2
2 3
3 4
1 5
2 6
3 7
4 8
5 6
6 7
7 8
5 9
6 10
7 11
8 12
9 10
10 11
11 12
9 13
10 14
11 15
12 16
13 14
14 15
15 16
```

command:
`./bin/fsm test/sample1_bin/ 4 4 v`

results:
```
4-FSM with threshold 4
-------
all patterns finished after 0.014621s
-------
all patterns finished after 0.005576s
-------
all patterns finished after 0.001604s
-------
all patterns finished after 0.015546s
-------
all patterns finished after 0.036467s
3 frequent patterns: 
[1,0-2,0][1,0-3,0][2,0-4,0](1,0~4,0)(2,0~3,0)(3,0~4,0): 15
[1,0-2,0][1,0-3,0][2,0-4,0][3,0-4,0](1,0~4,0)(2,0~3,0): 15
[1,0-2,0][1,0-3,0][1,0-4,0](2,0~3,0)(2,0~4,0)(3,0~4,0): 11
finished in 0.15677s
```

I'm not sure how to interpret the results. For example, the `[2,0-4,0]` probably represent an edge between vertex 2 and vertex 4? But there isn't such an edge in the input graph. Also, I'm not sure what's the difference between `[]` pairs and `()` pairs?

Thanks for your help!

**Comment by kjamsh** [comment]
Hi Licheng,

Thanks for reaching out! I'm having trouble reproducing the crash. `convert_data` seems to handle that input fine on my machine. Could you tell me more about the environment? What is your compiler version? Did you use the TBB library in the repo or one that's installed on your computer? Have you made any changes to the code? I'd love to get to the bottom of this :)

As for interpreting the results: although it's called frequent subgraph mining, the application returns the frequent _patterns_ instead. So [2,0-4,0] doesn't refer to an edge in the data graph, but an edge in a pattern graph. What Peregrine is saying is that there are 3 vertex-induced patterns with 4 vertices whose matches in the data graph meet the support threshold of 4. The `()` pairs encode anti-edges. For example the anti-edge `(1,0~4,0)` in the first pattern means that no matches for pattern vertex 1 are connected to the matches for vertex 4. The paper contains more information on this.

Let me know if you have any other questions!

**Comment by Licheng-Guo** [comment]
Hi Kasra,

Thanks for your explanation!

For the `convert_data` issue, it seems that it will only crash on tiny graphs. I'm running Ubuntu 18.04 with g++-10 and I did not make any modification to the code.

Thanks for clarifying the result format! In my scenario I need to know all the subgraphs of each pattern, so I wonder if there is an easy way to dump the actual subgraphs for each pattern?

Thanks a lot for your help!

Best,
Licheng

**Comment by kjamsh** [comment]
I'm happy to help! You have to make a couple modifications to the sample application in order to output subgraphs. I'd prefer we discuss that over email so we can keep the issue board focused. If you shoot me an email (the address is on my profile) with what kind of output you want and the the size of graphs you're working with I can suggest an appropriate method. 

Coming back to the crashes, do you mind attaching the exact files you passed to `convert_data`?

**Comment by Licheng-Guo** [comment]
Sure, I attached two files. "sample2.txt" will work while "sample3.txt" will segfault.

[sample2.txt](https://github.com/pdclab/peregrine/files/6314063/sample2.txt)
[sample3.txt](https://github.com/pdclab/peregrine/files/6314064/sample3.txt)

**Comment by kjamsh** [comment]
I just pushed a fix! Let me know if you have any other issues, or if this one is persisting.

**Comment by lady-bluecopper** [comment]
Hello! I also get a segmentation fault when trying to convert a big graph (Nodes=4589876, Edges=43968798). The files are huge and GitHub does not allow me to attach them, but I am uploading them here: https://www.dropbox.com/sh/0dyctovvq6z1uf0/AAALfHnYbn3fXQZ6AlEfyhWaa?dl=0
I run the command: 
`bin/convert_data data/peregrine_format/youtube_edges.txt data/peregrine_format/youtube_labels.txt data/youtube/`
I hope you can help me! 
Thanks,
Giulia
