### ISSUE TITLE
Way to output found embeddings?

### ISSUE THREAD

**Issue by sherlockwu** [pdclab/peregrine#11]
Hi authors,

Thank you for this excellent graph mining codebase. 

I'm wondering is there an argument to output all found embeddings that fit the pattern? (rather than just produce counted numbers)

Thanks

Kan

**Comment by kjamsh** [comment]
Hi Kan,

Thanks for your interest!

This has been a common request, so I went ahead and implemented native support for outputting matches to disk in 970b0be.
You can take a look at the README and the sample application in `apps/output.cc` to see how it works.

Let me know if you face any issues with it, or if there's anything else I can help you with :)

**Comment by sherlockwu** [comment]
Thanks for the effort! That helps.
