### ISSUE TITLE
Unable to compile on MacOS

### ISSUE THREAD

**Issue by IIMP** [pdclab/peregrine#12]
sorry to bother, I have a trouble about compiling the program on MacOS.
It shows that the compiler cannot find some symbols, as details pasted below.
========================================================
Undefined symbols for architecture x86_64:
  "__ZN3tbb8internal23allocate_via_handler_v3Em", referenced from:
      __ZN3tbb10interface58internal25concurrent_unordered_baseINS0_31concurrent_unordered_map_traitsISt6vectorIjSaIjEEyNS1_12hash_compareIS6_St4hashIS6_ESt8equal_toIS6_EEENS_13tbb_allocatorISt4pairIKS6_yEEELb0EEEE11init_bucketEm in ccDGi3UY.o
      __ZN3tbb10interface524concurrent_unordered_mapISt6vectorIjSaIjEEySt4hashIS4_ESt8equal_toIS4_ENS_13tbb_allocatorISt4pairIKS4_yEEEEixERSB_ in ccDGi3UY.o
      __ZN9Peregrine11match_multiISt6vectorIjSaIjEE15DiscoveryDomainILj1EELNS_14OnTheFlyOptionE1ELNS_15StoppableOptionE1ELNS_12OutputOptionE1ERKZ4mainEUlOT_OT0_E0_RZNS_5matchIS3_S5_LS6_1ELS7_1ERNS_9DataGraphESF_Z4mainEUlSA_E_LS8_1EEENSt11conditionalIXeqT6_LS8_0EES1_ISt5tupleIJNS_10SmallGraphEDTclcl7declvalIT5_EEcl7declvalISB_EEEENSt10filesystem7__cxx114pathEEESaISS_EES1_ISt4pairISM_SO_ESaISW_EEE4typeEOT3_RKS1_ISM_SaISM_EEjOT4_SN_EUlSA_E_EENSK_IXeqT3_LS8_0EESU_SY_E4typeES18_OSN_jS16_ in ccDGi3UY.o
      __ZN9Peregrine11match_multiISt6vectorIjSaIjEE6DomainLNS_14OnTheFlyOptionE1ELNS_15StoppableOptionE1ELNS_12OutputOptionE1ERKZ4mainEUlOT_OT0_E1_RZNS_5matchIS3_S4_LS5_1ELS6_1ERNS_9DataGraphESE_Z4mainEUlS9_E_LS7_1EEENSt11conditionalIXeqT6_LS7_0EES1_ISt5tupleIJNS_10SmallGraphEDTclcl7declvalIT5_EEcl7declvalISA_EEEENSt10filesystem7__cxx114pathEEESaISR_EES1_ISt4pairISL_SN_ESaISV_EEE4typeEOT3_RKS1_ISL_SaISL_EEjOT4_SM_EUlS9_E_EENSJ_IXeqT3_LS7_0EEST_SX_E4typeES17_OSM_jS15_ in ccDGi3UY.o
  "__ZN3tbb8internal25deallocate_via_handler_v3EPv", referenced from:
      __ZN3tbb10interface58internal18split_ordered_listISt4pairIKSt6vectorIjSaIjEEyENS_13tbb_allocatorIS8_EEED1Ev in ccDGi3UY.o
      __ZN9Peregrine13MapAggregatorISt6vectorIjSaIjEE15DiscoveryDomainILj1EELNS_14OnTheFlyOptionE1ELNS_15StoppableOptionE1ERZNS_5matchIS3_S5_LS6_1ELS7_1ERNS_9DataGraphERKZ4mainEUlOT_OT0_E0_Z4mainEUlSC_E_LNS_12OutputOptionE1EEENSt11conditionalIXeqT6_LSJ_0EES1_ISt5tupleIJNS_10SmallGraphEDTclcl7declvalIT5_EEcl7declvalISD_EEEENSt10filesystem7__cxx114pathEEESaISS_EES1_ISt4pairISM_SO_ESaISW_EEE4typeEOT3_RKS1_ISM_SaISM_EEjOT4_SN_EUlSC_E_LSJ_1EED1Ev in ccDGi3UY.o
      __ZN3tbb10interface58internal25concurrent_unordered_baseINS0_31concurrent_unordered_map_traitsISt6vectorIjSaIjEEyNS1_12hash_compareIS6_St4hashIS6_ESt8equal_toIS6_EEENS_13tbb_allocatorISt4pairIKS6_yEEELb0EEEE11init_bucketEm in ccDGi3UY.o
      __ZN3tbb10interface524concurrent_unordered_mapISt6vectorIjSaIjEEySt4hashIS4_ESt8equal_toIS4_ENS_13tbb_allocatorISt4pairIKS4_yEEEEixERSB_ in ccDGi3UY.o
      __ZN9Peregrine11match_multiISt6vectorIjSaIjEE15DiscoveryDomainILj1EELNS_14OnTheFlyOptionE1ELNS_15StoppableOptionE1ELNS_12OutputOptionE1ERKZ4mainEUlOT_OT0_E0_RZNS_5matchIS3_S5_LS6_1ELS7_1ERNS_9DataGraphESF_Z4mainEUlSA_E_LS8_1EEENSt11conditionalIXeqT6_LS8_0EES1_ISt5tupleIJNS_10SmallGraphEDTclcl7declvalIT5_EEcl7declvalISB_EEEENSt10filesystem7__cxx114pathEEESaISS_EES1_ISt4pairISM_SO_ESaISW_EEE4typeEOT3_RKS1_ISM_SaISM_EEjOT4_SN_EUlSA_E_EENSK_IXeqT3_LS8_0EESU_SY_E4typeES18_OSN_jS16_ in ccDGi3UY.o
      __ZN9Peregrine11match_multiISt6vectorIjSaIjEE6DomainLNS_14OnTheFlyOptionE1ELNS_15StoppableOptionE1ELNS_12OutputOptionE1ERKZ4mainEUlOT_OT0_E1_RZNS_5matchIS3_S4_LS5_1ELS6_1ERNS_9DataGraphESE_Z4mainEUlS9_E_LS7_1EEENSt11conditionalIXeqT6_LS7_0EES1_ISt5tupleIJNS_10SmallGraphEDTclcl7declvalIT5_EEcl7declvalISA_EEEENSt10filesystem7__cxx114pathEEESaISR_EES1_ISt4pairISL_SN_ESaISV_EEE4typeEOT3_RKS1_ISL_SaISL_EEjOT4_SM_EUlS9_E_EENSJ_IXeqT3_LS7_0EEST_SX_E4typeES17_OSM_jS15_ in ccDGi3UY.o
      __ZN9Peregrine11match_multiISt6vectorIjSaIjEE6DomainLNS_14OnTheFlyOptionE1ELNS_15StoppableOptionE1ELNS_12OutputOptionE1ERKZ4mainEUlOT_OT0_E1_RZNS_5matchIS3_S4_LS5_1ELS6_1ERNS_9DataGraphESE_Z4mainEUlS9_E_LS7_1EEENSt11conditionalIXeqT6_LS7_0EES1_ISt5tupleIJNS_10SmallGraphEDTclcl7declvalIT5_EEcl7declvalISA_EEEENSt10filesystem7__cxx114pathEEESaISR_EES1_ISt4pairISL_SN_ESaISV_EEE4typeEOT3_RKS1_ISL_SaISL_EEjOT4_SM_EUlS9_E_EENSJ_IXeqT3_LS7_0EEST_SX_E4typeES17_OSM_jS15_.cold in ccDGi3UY.o
      ...
ld: symbol(s) not found for architecture x86_64

**Comment by kjamsh** [comment]
Hi! No bother at all, thanks for your interest.

This seems like a TBB problem. The `tbb2020` folder included in this repository is specifically for Linux (as that is the main operating system we support at the moment.) You should install a [TBB distribution](https://github.com/oneapi-src/oneTBB/releases/tag/v2021.3.0) native to your system.

You can then ignore the `source tbb2020/bin/tbbvars.sh intel64` commands in the README when invoking Peregrine.

Let me know if this solves the problem!

**Comment by kjamsh** [comment]
For lack of updates, I'm going to close this issue. Feel free to open another one if you run into more trouble!
