### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by jiangxing2001** [pdclab/peregrine#19]
Can you provide the patent dataset file.
Looking forward to your reply.

**Comment by kjamsh** [comment]
Hi!

You can find the unlabeled patents dataset on [SNAP](https://snap.stanford.edu/data/cit-Patents.html). The labeled dataset was compiled using the original files from [NBER](https://www.nber.org/research/data/us-patents). For future reference, the paper contains citations for all the datasets.

**Comment by jiangxing2001** [comment]
Hi!
I want to change the output.After reading the&nbsp; code,I modify the fsm.cc,but the output isn't changed.Did I find the wrong file?
Looking forward to your reply！


派大星?
***@***.***







&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pdclab/peregrine"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月3日(星期天) 凌晨2:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pdclab/peregrine] About the dataset (Issue #19)





 
Hi!
 
You can find the unlabeled patents dataset on SNAP. The labeled dataset was compiled using the original files from NBER. For future reference, the paper contains citations for all the datasets.
