### ISSUE TITLE
Understanding output

### ISSUE THREAD

**Issue by zwucd166** [pdclab/peregrine#20]
Hello,

For the sample FSM app in the README, the output is:

Frequent patterns:
[1,0-2,0][1,0-3,0][2,0-4,0]: 303
[1,1-2,1][1,1-3,1][2,1-4,1]: 335

I'm struggling to understand what this output means. What does the numbers in the brackets corresponds to?

**Comment by kjamsh** [comment]
Hi,

This is a format I adopted from previous graph mining systems Arabesque and Fractal. Patterns are encoded as a list of edges `[u,l1-v,l2]` representing an edge `(u, v)` and specifying that vertex `u` has label `l1` and vertex `v` has label `l2`. 

So `[1,0-2,0][1,0-3,0][2,0-4,0]` represents a pattern with edges `(1, 2)(1,3)(2,4)` where all vertices have label 0.

Each pattern corresponds to an MNI support value (i.e., these two patterns have support 303 and 335, respectively).

Hope this helps.
