### ISSUE TITLE
A question about subgraph match

### ISSUE THREAD

**Issue by ErvinXie** [pdclab/peregrine#23]
Hello guys,

I have a ring data graph, and a chain pattern graph like these.
Data
1 2
2 3
3 4
4 5 
5 1
Pattern
1 2
2 3
3 4

I was expecting that the match results should be 1 2 3 4, 2 3 4 5, 3 4 5 1, 4 5 1 2, and 5 1 2 3. But Peregrine only outputs 4 3 2 1 
and 5 4 3 2 . Is this correct? I am not sure whether this is due to the canonical checks. How should I find the later 3 match?

**Comment by kjamsh** [comment]
Hi Ervin, could you share more details about what you're running? Your results are definitely not expected. I cloned a fresh copy of peregrine and ran `bin/count`, `bin/enumerate` and `bin/output` with that data graph and pattern and got 5 subgraphs each time. So I'm curious which platform you are running on and whether the provided applications also give incorrect results. Please let me know and I'll happily look further into this!

**Comment by ErvinXie** [comment]
Hi kjamsh, thanks for your reply. I write my own program to match this pattern, because I want to these matched pattern for further computation. The program is something like this.
```
SmallGraph p(pattern_path);
DataGraph dg(graph_path);
std::vector<SmallGraph> patterns = {p};
 const auto callback = [&dg](auto &&handle, auto &&match) {
    handle.map(match.pattern, 1);
    for (size_t i = 0; i < match.mapping.size(); i++) {
      std::cout<< dg.original_id(match.mapping[i])<<" ";
    }
    std::cout<<std::endl;
  };

  auto results = output<Pattern, uint64_t, AT_THE_END, UNSTOPPABLE>(
      dg, patterns, std::thread::hardware_concurrency(), callback);
```
The data graph and pattern graph are just what I provided. 
Is the callback function correct?

**Comment by kjamsh** [comment]
I believe the issue is with using `std::cout` in the callback, since it is not threadsafe and the callback is invoked simultaneously by multiple threads. You can confirm if this is the issue by using only one thread (instead of std::thread::hardware_concurrency()).

If you need to write out the subgraphs I suggest using the provided thread-safe output functionality in Peregrine (i.e., use `handle.template output<CSV>(match.mapping);` instead of directly writing to stdout). Let me know if this helps!

**Comment by ErvinXie** [comment]
I figured out why this would happen. The last edge in edges.txt must end with a '\n'. During my test, convert_data ignored the last edge 5 1, so Peregrine only output 2 results. 

Thanks for your reply!
