### ISSUE TITLE
Issue with make command 

### ISSUE THREAD

**Issue by Hitarth24** [pdclab/peregrine#25]
/usr/bin/ld: cannot open output file bin//count: No such file or directory
collect2: error: ld returned 1 exit status
Makefile:24: recipe for target 'count' failed
make: *** [count] Error 1
make: *** Waiting for unfinished jobs....
/usr/bin/ld: cannot open output file bin//existence-query: No such file or directory
collect2: error: ld returned 1 exit status
Makefile:21: recipe for target 'existence-query' failed
make: *** [existence-query] Error 1
/usr/bin/ld: cannot open output file bin//fsm: No such file or directory
collect2: error: ld returned 1 exit status
Makefile:18: recipe for target 'fsm' failed
make: *** [fsm] Error 1

**Comment by kjamsh** [comment]
Hi Hitarth, does the `bin/` directory exist?
