### ISSUE TITLE
TBB compiled with gcc 4.7

### ISSUE THREAD

**Issue by sth1997** [pdclab/peregrine#3]
Since Peregrine requires C++20 support, I'm using gcc 10.1.0 to compile Peregrine.
When I run `source tbb2019/bin/tbbvars.sh intel64`, it told me `ERROR: libtbb.so.2 library does not exist in /home/sth/download/peregrine/tbb2019//lib/intel64/gcc4.1.`
I found this code in tbbvars.sh:

get_library_directory () {

    gcc_version_full=$(gcc --version | grep "gcc" | egrep -o " [0-9]+\.[0-9]+\.[0-9]+.*" | sed -e "s/^\ //")
    if [ $? -eq 0 ]; then
        gcc_version=$(echo "$gcc_version_full" | egrep -o "^[0-9]+\.[0-9]+\.[0-9]+")
    fi
    case "${gcc_version}" in
    4.[7-9]*|[5-9]* )
        lib_dir="gcc4.7";;
    4.[4-6]* )
        lib_dir="gcc4.4";;
    * )
        lib_dir="gcc4.1";;
    esac
    echo $lib_dir
}
It seems that gcc 10.1.0 is regarded as gcc4.1, and the directory `/tbb2019//lib/intel64/gcc4.1` doesn't exist.
What should I do? Do I need to compile TBB2019 with gcc 10.1.0 by myself?

**Comment by kjamsh** [comment]
Hi there! Thanks for bringing this to my attention.

It just needed a version bump. If you pull again and substitute `tbb2020` for `tbb2019` it should work. Also, depending on your platform, you might be able to just install the latest TBB so you don't have to keep running `tbbvars.sh`.

Let me know if you encounter any further issues!
