### ISSUE TITLE
Unable to compile Peregrine on Ubuntu 16.04

### ISSUE THREAD

**Issue by Kiran-r** [pdclab/peregrine#5]
Hi,

I am unable to compile Peregrine on ubuntu 16.04 with GCC 10.2 or 9.3. I am setting the TBB available in the repo by:

`source tbb2020/bin/tbbvars.sh intel64`

However, I see linker errors when compiling as shown below. Do you have any workarounds for this problem?

```In function `Peregrine::DataConverter::convert_data(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
DataConverter.cc:(.text+0x42a6): undefined reference to `tbb::interface7::internal::isolate_within_arena(tbb::interface7::internal::delegate_base&, long)'
DataConverter.cc:(.text+0x44da): undefined reference to `tbb::interface7::internal::isolate_within_arena(tbb::interface7::internal::delegate_base&, long)'
DataConverter.cc:(.text+0x46d7): undefined reference to `tbb::interface7::internal::isolate_within_arena(tbb::interface7::internal::delegate_base&, long)'
DataConverter.cc:(.text+0x47fc): undefined reference to `tbb::interface7::internal::isolate_within_arena(tbb::interface7::internal::delegate_base&, long)'
DataConverter.cc:(.text+0x4c25): undefined reference to `tbb::interface7::internal::isolate_within_arena(tbb::interface7::internal::delegate_base&, long)'
collect2: error: ld returned 1 exit status```

P.S. This problem is only on `16.04`. It compiles and runs fine in `18.04` and `20.04`.

**Comment by kjamsh** [comment]
Hi Kiran,

Thanks for your interest! I haven't tried building Peregrine on 16.04 before. I will look into it and get back to you.

In the meantime, you can try an [older TBB release](https://github.com/oneapi-src/oneTBB/releases) to see if that works. The original build was with GCC 9.2.1 and TBB2019 on Ubuntu 18.04, so the releases from 2019 and 2018 might be good candidates.

Let me know if you figure it out!

**Comment by kjamsh** [comment]
Fixed by #6, thanks Kiran!
