### ISSUE TITLE
Question - newer algorithm identification and improvements?

### ISSUE THREAD

**Issue by unibum** [pdclab/peregrine#9]
Hi,

hopefully an easy question.
The performance of your solution is quite amazing.
I see other Graph solutions are implementing newer and better performing algorithms i.e. https://arxiv.org/pdf/1910.05971.pdf into Gunrock/GraphBlast as example.

My question is, are you actively looking for newer algorithms to implement/improve the performance of your solution? or is your solution more academic and in a kind of snapshot in time/maintenance/bug handling mode only.

Thanks in advance!

**Comment by kjamsh** [comment]
Hi! Thanks for your interest.

This repo is being actively developed to improve Peregrine's performance and expand its capabilities, and I'll happily accept PRs that add new applications.

Feel free to reach out to us directly (kjamshid at sfu.ca  and  keval at sfu.ca) if you have more questions.
